POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "fullname": "Asaad Saad",
    "email": "daddy@miu.edu",
    "password": "123456"
}
###
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "asaad@miu.edu",
    "password": "123456"
}